"""
Data structures for patient life background generation.
"""
from dataclasses import dataclass
from typing import List


@dataclass
class LifeFacet:
    """
    A single life facet describing one aspect of the patient's life context.
    
    Attributes
    ----------
    category : str
        Category ID from LIFE_FACET_CATEGORIES
    salience : str
        "low", "med", or "high" - how central this facet is to the patient's life
    description : str
        1-2 sentences, max ~35-40 words, describing this facet for this patient
    """
    category: str
    salience: str
    description: str


@dataclass
class PatientLifeBackground:
    """
    Rich life background for a patient, generated by the background writer.
    
    Attributes
    ----------
    name : str
        Short name for the patient
    age_range : str
        Age bracket, e.g., "late 20s", "early 40s"
    pronouns : str
        Pronoun phrase, e.g., "she/her", "he/him", "they/them"
    core_roles : List[str]
        Main roles in life, e.g., ["graduate student", "older sibling"]
    core_relationships : List[str]
        1-3 short phrases about important people or relationship patterns
    core_stressor_summary : str
        1-2 short sentences linking to context_domains and depression profile
    life_facets : List[LifeFacet]
        List of life facets providing detailed context
    """
    name: str
    age_range: str
    pronouns: str
    core_roles: List[str]
    core_relationships: List[str]
    core_stressor_summary: str
    life_facets: List[LifeFacet]
